-- SCRIPT DE CONFIGURACIÓN PARA SUPABASE
-- Copia y pega todo este código en el SQL Editor de Supabase

-- 1. Crear la tabla 'cars'
CREATE TABLE IF NOT EXISTS public.cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    price BIGINT NOT NULL,
    mileage INTEGER NOT NULL,
    transmission TEXT NOT NULL,
    fuel_type TEXT NOT NULL,
    image_url TEXT,
    description TEXT,
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Habilitar Seguridad de Nivel de Fila (RLS)
-- Esto es necesario para que Supabase permita leer los datos
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas de acceso (Permitir que cualquiera lea e inserte datos)
-- Nota: En producción querrás restringir la inserción, pero para empezar esto funciona:
CREATE POLICY "Permitir lectura pública" ON public.cars FOR SELECT USING (true);
CREATE POLICY "Permitir inserción pública" ON public.cars FOR INSERT WITH CHECK (true);

-- 4. Insertar algunos carros de ejemplo para que la página no se vea vacía
INSERT INTO public.cars (make, model, year, price, mileage, transmission, fuel_type, image_url, description)
VALUES 
('Toyota', 'Corolla', 2022, 85000000, 15000, 'Automatic', 'Gasoline', 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&q=80&w=1000', 'Excelente estado, único dueño, mantenimiento al día.'),
('Mazda', 'CX-5', 2021, 115000000, 28000, 'Automatic', 'Gasoline', 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=1000', 'Versión Grand Touring, impecable, papeles al día.'),
('Chevrolet', 'Onix', 2023, 62000000, 5000, 'Manual', 'Gasoline', 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1000', 'Como nuevo, poco kilometraje, gran ahorro de combustible.');
