export const BRANDS_DATA = [
  { name: "Audi", hasModels: true, models: [
    { name: "A3", count: 0 },
    { name: "A4", count: 0 },
    { name: "Q3", count: 0 },
    { name: "Q5", count: 0 },
  ]},
  { name: "Bmw", hasModels: true, models: [
    { name: "Serie 3", count: 0 },
    { name: "X1", count: 0 },
    { name: "X3", count: 0 },
    { name: "X5", count: 0 },
  ]},
  { name: "Chery", hasModels: true, models: [
    { name: "Tiggo", count: 0 },
    { name: "QQ", count: 0 },
  ]},
  { name: "Chevrolet", hasModels: true, models: [
    { name: "Alto", count: 1 },
    { name: "Astra", count: 0 },
    { name: "Aveo", count: 8 },
    { name: "Beat", count: 12 },
    { name: "Blazer", count: 0 },
    { name: "Captiva Sport", count: 5 },
    { name: "Cobalt", count: 6 },
    { name: "Cruze", count: 0 },
    { name: "D-max", count: 3 },
    { name: "Grand Vitara", count: 0 },
    { name: "joy", count: 10 },
    { name: "Luv", count: 0 },
    { name: "Montana", count: 0 },
    { name: "N-300", count: 0 },
    { name: "NPR", count: 1 },
    { name: "Onix", count: 24 },
    { name: "Optra", count: 1 },
    { name: "Orlando", count: 1 },
    { name: "Sail", count: 11 },
    { name: "Sonic", count: 1 },
    { name: "Spark", count: 5 },
    { name: "Spark Gt", count: 16 },
    { name: "Spark Life", count: 0 },
    { name: "Sprint", count: 0 },
    { name: "Tracker", count: 13 },
    { name: "Vagon R", count: 0 },
  ]},
  { name: "Dodge", hasModels: true, models: [
    { name: "Journey", count: 0 },
    { name: "Ram", count: 0 },
  ]},
  { name: "Fiat", hasModels: true, models: [
    { name: "Uno", count: 0 },
    { name: "Palio", count: 0 },
    { name: "Strada", count: 0 },
  ]},
  { name: "Ford", hasModels: true, models: [
    { name: "Fiesta", count: 0 },
    { name: "EcoSport", count: 0 },
    { name: "Escape", count: 0 },
    { name: "Explorer", count: 0 },
    { name: "Ranger", count: 0 },
    { name: "F-150", count: 0 },
  ]},
  { name: "Hiundai", hasModels: true, models: [
    { name: "i10", count: 0 },
    { name: "Accent", count: 0 },
    { name: "Tucson", count: 0 },
    { name: "Santa Fe", count: 0 },
    { name: "Creta", count: 0 },
  ]},
  { name: "Jaguar", hasModels: false },
  { name: "Jeep", hasModels: true, models: [
    { name: "Grand Cherokee", count: 0 },
    { name: "Wrangler", count: 0 },
    { name: "Compass", count: 0 },
    { name: "Renegade", count: 0 },
  ]},
  { name: "Kia", hasModels: true, models: [
    { name: "Picanto", count: 0 },
    { name: "Rio", count: 0 },
    { name: "Cerato", count: 0 },
    { name: "Sportage", count: 0 },
    { name: "Sorento", count: 0 },
  ]},
  { name: "Mazda", hasModels: true, models: [
    { name: "Mazda 2", count: 0 },
    { name: "Mazda 3", count: 0 },
    { name: "CX-3", count: 0 },
    { name: "CX-30", count: 0 },
    { name: "CX-5", count: 0 },
    { name: "CX-9", count: 0 },
  ]},
  { name: "Mercedes Benz", hasModels: true, models: [
    { name: "Clase A", count: 0 },
    { name: "Clase C", count: 0 },
    { name: "GLA", count: 0 },
    { name: "GLC", count: 0 },
  ]},
  { name: "Mitsubishi", hasModels: true, models: [
    { name: "L200", count: 0 },
    { name: "Montero", count: 0 },
    { name: "ASX", count: 0 },
    { name: "Outlander", count: 0 },
  ]},
  { name: "Nissan", hasModels: true, models: [
    { name: "March", count: 0 },
    { name: "Versa", count: 0 },
    { name: "Sentra", count: 0 },
    { name: "Frontier", count: 0 },
    { name: "Qashqai", count: 0 },
    { name: "X-Trail", count: 0 },
    { name: "Kicks", count: 0 },
  ]},
  { name: "Peugeot", hasModels: true, models: [
    { name: "208", count: 0 },
    { name: "2008", count: 0 },
    { name: "3008", count: 0 },
  ]},
  { name: "Renault", hasModels: true, models: [
    { name: "Logan", count: 0 },
    { name: "Sandero", count: 0 },
    { name: "Stepway", count: 0 },
    { name: "Duster", count: 0 },
    { name: "Kwid", count: 0 },
    { name: "Koleos", count: 0 },
    { name: "Captur", count: 0 },
    { name: "Oroch", count: 0 },
    { name: "Twingo", count: 0 },
    { name: "Clio", count: 0 },
  ]},
  { name: "Ssangyong", hasModels: true, models: [
    { name: "Actyon", count: 0 },
    { name: "Korando", count: 0 },
    { name: "Tivoli", count: 0 },
  ]},
  { name: "Suzuki", hasModels: true, models: [
    { name: "Swift", count: 0 },
    { name: "Vitara", count: 0 },
    { name: "Jimny", count: 0 },
    { name: "S-Cross", count: 0 },
    { name: "Celerio", count: 0 },
  ]},
  { name: "Toyota", hasModels: true, models: [
    { name: "Corolla", count: 0 },
    { name: "Hilux", count: 0 },
    { name: "Fortuner", count: 0 },
    { name: "Prado", count: 0 },
    { name: "Land Cruiser", count: 0 },
    { name: "RAV4", count: 0 },
    { name: "Yaris", count: 0 },
    { name: "4Runner", count: 0 },
  ]},
  { name: "Volkswagen", hasModels: true, models: [
    { name: "Gol", count: 0 },
    { name: "Jetta", count: 0 },
    { name: "Amarok", count: 0 },
    { name: "Tiguan", count: 0 },
    { name: "T-Cross", count: 0 },
    { name: "Nivus", count: 0 },
  ]},
  { name: "Volvo", hasModels: true, models: [
    { name: "XC40", count: 0 },
    { name: "XC60", count: 0 },
    { name: "XC90", count: 0 },
  ]},
];
