export const BRANDS_DATA = [
  { name: "Audi", hasModels: false },
  { name: "Bmw", hasModels: false },
  { name: "Chery", hasModels: false },
  { name: "Chevrolet", hasModels: true, models: [
    { name: "Alto", count: 1 },
    { name: "Astra", count: 0 },
    { name: "Aveo", count: 8 },
    { name: "Beat", count: 12 },
    { name: "Blazer", count: 0 },
    { name: "Captiva Sport", count: 5 },
    { name: "Cobalt", count: 6 },
    { name: "Cruze", count: 0 },
    { name: "D-max", count: 3 },
    { name: "Grand Vitara", count: 0 },
    { name: "joy", count: 10 },
    { name: "Luv", count: 0 },
    { name: "Montana", count: 0 },
    { name: "N-300", count: 0 },
    { name: "NPR", count: 1 },
    { name: "Onix", count: 24 },
    { name: "Optra", count: 1 },
    { name: "Orlando", count: 1 },
    { name: "Sail", count: 11 },
    { name: "Sonic", count: 1 },
    { name: "Spark", count: 5 },
    { name: "Spark Gt", count: 16 },
    { name: "Spark Life", count: 0 },
    { name: "Sprint", count: 0 },
    { name: "Tracker", count: 13 },
    { name: "Vagon R", count: 0 },
  ]},
  { name: "Dodge", hasModels: true },
  { name: "Fiat", hasModels: false },
  { name: "Ford", hasModels: true },
  { name: "Hiundai", hasModels: true },
  { name: "Jaguar", hasModels: false },
  { name: "Jeep", hasModels: true },
  { name: "Kia", hasModels: true },
  { name: "Mazda", hasModels: true },
  { name: "Mercedes Benz", hasModels: false },
  { name: "Mitsubishi", hasModels: false },
  { name: "Nissan", hasModels: true },
  { name: "Peugeot", hasModels: false },
  { name: "Renault", hasModels: true },
  { name: "Ssangyong", hasModels: false },
  { name: "Suzuki", hasModels: true },
  { name: "Toyota", hasModels: true },
  { name: "Volkswagen", hasModels: false },
  { name: "Volvo", hasModels: false },
];
